In [6]:
import pandas as pd

# CSVファイルを読み込む
df = pd.read_csv('data6.csv')

df.head()

,コード,年度,総資産,純資産,株主資本,利益剰余金,短期借入金,長期借入金,BPS,自己資本比率,企業名,業界
0,1301,2022/03,130460000000,42174000000,39072000000,32507000000,15714000000,27021000000,3969.60,32.7,極洋,水産・農林業
1,1332,2022/03,505731000000,208598000000,172889000000,121472000000,83197000000,94939000000,609.82,37.5,ニッスイ,水産・農林業
2,1333,2022/03,548603000000,187895000000,153291000000,91611000000,138467000000,112136000000,3043.95,29.2,マルハニチロ,水産・農林業
3,1352,2022/03,41116000000,8842000000,7804000000,4100000000,2300000000,17138000000,936.39,19.1,ホウスイ,卸売業
4,1375,2022/03,36096000000,10470000000,10471000000,16411000000,-,17314000000,262.62,29.0,雪国まいたけ,水産・農林業

In [7]:
df = df.drop(['コード','年度','業界'],axis=1)
df.head()

,総資産,純資産,株主資本,利益剰余金,短期借入金,長期借入金,BPS,自己資本比率,企業名
0,130460000000,42174000000,39072000000,32507000000,15714000000,27021000000,3969.60,32.7,極洋
1,505731000000,208598000000,172889000000,121472000000,83197000000,94939000000,609.82,37.5,ニッスイ
2,548603000000,187895000000,153291000000,91611000000,138467000000,112136000000,3043.95,29.2,マルハニチロ
3,41116000000,8842000000,7804000000,4100000000,2300000000,17138000000,936.39,19.1,ホウスイ
4,36096000000,10470000000,10471000000,16411000000,-,17314000000,262.62,29.0,雪国まいたけ

In [8]:
df.describe()

,総資産,純資産,株主資本,利益剰余金,BPS,自己資本比率
count,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03,1000.000000
mean,1.553648e+11,7.448982e+10,6.727312e+10,5.133400e+10,2.478915e+07,50.811400
std,5.925131e+11,2.715187e+11,2.356659e+11,1.864432e+11,7.838563e+08,20.636794
min,5.120720e+08,-4.205970e+08,-4.226430e+08,-5.818400e+10,-1.319000e+02,-29.600000
25%,8.059737e+09,3.855838e+09,3.750104e+09,1.634257e+09,3.385725e+02,35.700000
50%,2.285248e+10,1.067639e+10,1.001937e+10,7.141000e+09,8.967700e+02,51.400000
75%,8.199350e+10,4.056436e+10,3.793965e+10,2.965500e+10,1.868085e+03,67.325000
max,1.055096e+13,4.038361e+12,3.540435e+12,3.089909e+12,2.478771e+10,96.100000